/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Counts of known runs in the active server process.
 */
export interface SystemRunCounts {
    /**
     * Total runs tracked by the server process.
     */
    'total'?: number;
    /**
     * Runs currently pending, runnable, or executing.
     */
    'active'?: number;
    /**
     * Runs currently occupying scheduler concurrency slots.
     */
    'scheduler_slots_used'?: number;
}
